import { useState } from "react";
import { backendHealth, generateVideo, refineVideo } from "../lib/backend";
import { CONTENT_TYPES, type ProjectState } from "../lib/types";

export default function VideoStep({
  project,
  update,
  onBack,
  onRestart,
}: {
  project: ProjectState;
  update: (patch: Partial<ProjectState>) => void;
  onBack: () => void;
  onRestart: () => void;
}) {
  const [rendering, setRendering] = useState(false);
  const [pct, setPct] = useState(0);
  const [label, setLabel] = useState("");
  const [result, setResult] = useState<{ videoUrl: string | null; message: string } | null>(null);
  const [prompt, setPrompt] = useState<string>(""); // the brief HeyGen used (for refining)
  const [feedback, setFeedback] = useState("");

  const onProgress = (p: { pct: number; step: string }) => {
    setPct(p.pct);
    setLabel(p.step);
  };

  const start = async () => {
    setRendering(true);
    setResult(null);
    setPct(0);
    setLabel("Starting…");
    const health = await backendHealth();
    if (!health.ok) {
      setResult({ videoUrl: null, message: "The studio engine isn't running. Start it with: npm run studio" });
      setRendering(false);
      return;
    }
    try {
      const r = await generateVideo(
        {
          audio: project.audioBlob,
          audioName: project.audioName,
          script: project.audioBlob ? undefined : project.script,
          audience: project.audience,
          contentType: project.contentType,
        },
        onProgress
      );
      finish(r);
    } catch (e) {
      setResult({ videoUrl: null, message: e instanceof Error ? e.message : "Something went wrong." });
      setRendering(false);
    }
  };

  const regenerate = async () => {
    if (!feedback.trim() || !prompt) return;
    setRendering(true);
    setResult(null);
    setPct(0);
    setLabel("Sending your changes to HeyGen…");
    try {
      const r = await refineVideo(prompt, feedback.trim(), project.contentType, onProgress);
      finish(r);
      setFeedback("");
    } catch (e) {
      setResult({ videoUrl: null, message: e instanceof Error ? e.message : "Regeneration failed." });
      setRendering(false);
    }
  };

  const finish = (r: { videoUrl: string | null; error?: string | null; prompt?: string }) => {
    if (r.videoUrl) {
      setResult({ videoUrl: r.videoUrl, message: "Your video is ready." });
      update({ videoUrl: r.videoUrl });
      if (r.prompt) setPrompt(r.prompt);
    } else {
      setResult({ videoUrl: null, message: r.error || "No video came back." });
    }
    setRendering(false);
  };

  const canStart = project.script.trim().length >= 10 || project.audioBlob;

  return (
    <section className="card">
      <h2>Create your video</h2>
      <p className="lead">
        Your voice or notes become a finished, production-ready video — generated by
        HeyGen's Video Agent: script, illustrated presenter, b-roll, animations, captions
        and music, all on-brand. Pick a type and press the bloom.
      </p>

      <div className="field">
        <label>Video type</label>
        <div className="engine-grid">
          {CONTENT_TYPES.map((c) => (
            <div
              key={c.id}
              className={`engine-card ${project.contentType === c.id ? "selected" : ""}`}
              onClick={() => !rendering && update({ contentType: c.id })}
            >
              <div className="e-ico">{c.ico}</div>
              <h3>{c.label}</h3>
              <p>{c.blurb}</p>
            </div>
          ))}
        </div>
      </div>

      {!rendering && !result && (
        <div className="actions">
          <button className="btn btn-secondary" onClick={onBack}>← Back</button>
          <button className="btn btn-bloom" onClick={start} disabled={!canStart}>
            🌸 Generate video
          </button>
        </div>
      )}

      {rendering && (
        <div className="render-stage">
          <div style={{ fontSize: 34 }}>🌸</div>
          <div className="progress-track"><div className="progress-fill" style={{ width: `${pct}%` }} /></div>
          <div className="muted">{label} · {pct}%</div>
          <p className="muted" style={{ fontSize: 12.5, marginTop: 8 }}>
            HeyGen's Video Agent is producing your video — this takes a few minutes for a
            polished result.
          </p>
        </div>
      )}

      {result && !rendering && (
        <>
          <div className="render-stage">
            {result.videoUrl ? (
              <video src={result.videoUrl} controls playsInline style={{ width: "100%", maxWidth: 480, borderRadius: 16 }} />
            ) : (
              <p style={{ lineHeight: 1.6 }}>{result.message}</p>
            )}
          </div>

          {result.videoUrl && (
            <>
              <div className="row" style={{ justifyContent: "center", gap: 12, marginTop: 16, flexWrap: "wrap" }}>
                <a className="btn btn-primary" href={result.videoUrl} download="florapeutic-video.mp4">
                  ⬇️ Download (high quality)
                </a>
                <a className="btn btn-secondary" href={result.videoUrl} target="_blank" rel="noreferrer">↗ Open full size</a>
              </div>

              {/* Feedback → regenerate with HeyGen */}
              <div className="field" style={{ marginTop: 26 }}>
                <label>Want changes? <span className="hint">— describe them and I'll regenerate</span></label>
                <textarea
                  rows={3}
                  placeholder="e.g. Make it more uplifting, slower pace, add a wedding scene, warmer music, end with the quote line…"
                  value={feedback}
                  onChange={(e) => setFeedback(e.target.value)}
                />
                <div className="row" style={{ marginTop: 10, gap: 12 }}>
                  <button className="btn btn-bloom" onClick={regenerate} disabled={!feedback.trim() || !prompt}>
                    ✨ Regenerate with changes
                  </button>
                  {!prompt && <span className="muted" style={{ fontSize: 12.5 }}>Refining is available for HeyGen videos.</span>}
                </div>
              </div>
            </>
          )}

          <div className="actions">
            <button className="btn btn-secondary" onClick={onBack}>← Back</button>
            <button className="btn btn-primary" onClick={onRestart}>＋ Create new</button>
          </div>
        </>
      )}
    </section>
  );
}
